In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

data = {
    'Weight':[303,370,298,277,377,299,382,374,303,309,359,366,311,302,373,305,371],
    'Colour':[3,1,3,3,4,3,1,4,4,3,1,1,3,3,4,3,3],
    'Label':['Banana','Apple','Banana','Banana','Apple','Banana','Apple',
             'Apple','Banana','Banana','Apple','Apple','Banana',
             'Banana','Apple','Banana','Apple']
}

df = pd.DataFrame(data)

df.head()

   Weight  Colour   Label
0     303       3  Banana
1     370       1   Apple
2     298       3  Banana
3     277       3  Banana
4     377       4   Apple

In [ ]:
print("Rows and Columns:", df.shape)

Rows and Columns: (17, 3)

In [ ]:
print(df.columns)

Index(['Weight', 'Colour', 'Label'], dtype='object')

In [ ]:
print(df.columns)

Index(['Weight', 'Colour', 'Label'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  17 non-null     int64
 1   Colour  17 non-null     int64
 2   Label   17 non-null     object
dtypes: int64(2), object(1)
memory usage: 540.0+ bytes

In [ ]:
df.describe()

           Weight     Colour
count   17.000000  17.000000
mean   334.058824   2.764706
std     37.332075   1.091410
min    277.000000   1.000000
25%    303.000000   3.000000
50%    311.000000   3.000000
75%    371.000000   3.000000
max    382.000000   4.000000

In [ ]:
df.isnull().sum()

Weight    0
Colour    0
Label     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Label'].unique()

array(['Banana', 'Apple'], dtype=object)

In [ ]:
df['Fruit_Size'] = df['Weight'].apply(
    lambda x: 'Heavy' if x > 340 else 'Light'
)

df.head()

   Weight  Colour   Label Fruit_Size
0     303       3  Banana      Light
1     370       1   Apple      Heavy
2     298       3  Banana      Light
3     277       3  Banana      Light
4     377       4   Apple      Heavy

In [ ]:
df['Label_Code'] = df['Label'].map({
    'Apple':1,
    'Banana':0
})

df.head()

   Weight  Colour   Label Fruit_Size  Label_Code
0     303       3  Banana      Light           0
1     370       1   Apple      Heavy           1
2     298       3  Banana      Light           0
3     277       3  Banana      Light           0
4     377       4   Apple      Heavy           1

In [ ]:
df.info()

df.head()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Weight      17 non-null     int64
 1   Colour      17 non-null     int64
 2   Label       17 non-null     object
 3   Fruit_Size  17 non-null     object
 4   Label_Code  17 non-null     int64
dtypes: int64(3), object(2)
memory usage: 812.0+ bytes

           Weight     Colour  Label_Code
count   17.000000  17.000000   17.000000
mean   334.058824   2.764706    0.470588
std     37.332075   1.091410    0.514496
min    277.000000   1.000000    0.000000
25%    303.000000   3.000000    0.000000
50%    311.000000   3.000000    0.000000
75%    371.000000   3.000000    1.000000
max    382.000000   4.000000    1.000000

In [ ]:
df.to_csv(
    'cleaned_fruit_dataset.csv',
    index=False
)

In [ ]:
from google.colab import files

files.download('cleaned_fruit_dataset.csv')